services:
  ais_net_receiver:
    container_name: ais-dotnet-receiver
    image: endjin/ais-dotnet-receiver:0.3.8-dockerize.1
    environment:
      - Ais__host=153.44.253.27
      - Ais__port=5631
      - Ais__loggerVerbosity=Minimal
      - Ais__statisticsPeriodicity=00:00:01:00
      - Ais__retryAttempts=5
      - Ais__retryPeriodicity=00:00:00:01
      - Storage__enableCapture=true
      - Storage__connectionString=${AIS_NET_RECEIVER_AZURE_CONNECTION_STRING}
      - Storage__containerName=nmea-ais-dev
      - Storage__writeBatchSize=500