services:
  ais.net.receiver.host.console:
    image: ${DOCKER_REGISTRY-}aisnetreceiverhostconsole
    build:
      context: .
      dockerfile: Ais.Net.Receiver.Host.Console/Dockerfile
    environment:
      - Ais__host=153.44.253.27
      - Ais__port=5631
      - Ais__loggerVerbosity=Minimal
      - Ais__statisticsPeriodicity=00:00:01:00
      - Ais__retryAttempts=100
      - Ais__retryPeriodicity=00:00:00:01
      - Storage__enableCapture=false
      - Storage__connectionString=${Azure_Storage_ConnectionString}
      - Storage__containerName=nmea-ais
      - Storage__writeBatchSize=500
