<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(EndjinProjectPropsPath)" Condition="$(EndjinProjectPropsPath) != ''" />
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
    <EndjinDisableCodeAnalysis>True</EndjinDisableCodeAnalysis>
  </PropertyGroup>

  <PropertyGroup>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageDescription>An Azure Blob based IStorageClient implmentation for persisting raw NMEA AIS sentences. Sponsored by endjin.</PackageDescription>
    <PackageTags>ais;aisvdm;aivdo;nmea;marine;gis;iot;aiforearth;microsoft;azure;blob;storage;endjin</PackageTags>
    <PackageReleaseNotes></PackageReleaseNotes>
  </PropertyGroup>
  
  <PropertyGroup>
    <NoWarn>RCS1029;SA1313;SA1009;SA1600;SA1591;CS1591;</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Endjin.RecommendedPractices.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="StyleCop.Analyzers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ais.Net.Receiver\Ais.Net.Receiver.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ais.Net.Receiver.Tests" />
  </ItemGroup>

</Project>
