<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(EndjinProjectPropsPath)" Condition="$(EndjinProjectPropsPath) != ''" />
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
    <EndjinDisableCodeAnalysis>True</EndjinDisableCodeAnalysis>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>RCS1029;SA1313;SA1009;SA1600;SA1591;CS1591;</NoWarn>
    <RootNamespace> </RootNamespace>
  </PropertyGroup>
  
  <PropertyGroup>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageDescription>Recieves Network streams of NMEA sentences and can decode AIS message types 1,2,3,5,18,19,24 Part 0, and 24 Part 1 into an IObservable of IAisMessage (See Ais.Net.Models). Sponsored by endjin.</PackageDescription>
    <PackageTags>ais;aisvdm;aivdo;nmea;marine;gis;iot;endjin</PackageTags>
    <PackageReleaseNotes></PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ais.Net.Models" Version="0.3.1" />
    <PackageReference Include="Polly.Core" Version="8.*" />
    <PackageReference Include="Endjin.RecommendedPractices.GitHub" Version="2.1.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.17.0" />
    <PackageReference Include="Spectre.IO" Version="0.23.0" />
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="StyleCop.Analyzers" Version="1.2.0-beta.321" />
  </ItemGroup>

</Project>
