<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Testing Platform -->
    <PackageReference Include="MSTest" Version="4.0.2" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="2.0.2" />
    
    <!-- Assertion Framework -->
    <PackageReference Include="Shouldly" Version="4.3.0" />
    
    <!-- Mocking Framework -->
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    
    <!-- Additional Tools -->
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Spectre.IO.Testing" Version="0.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ais.Net.Receiver\Ais.Net.Receiver.csproj" />
  </ItemGroup>
</Project>
